name: Update PHP 8.0 CLI CI Variant

on:
  push:
    paths:
      - '!**'
      - '.github/workflows/php-8.0-cli.yml'
      - 'php-8.0-cli/**'

jobs:
  update:
    name: Build and Publish PHP 8.0 CLI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build PHP 8.0 CLI
        run: docker build php-8.0-cli --tag ghcr.io/makadev/ci-images/php:8.0-cli
      - name: Push PHP 8.0 CLI to GitHub Container Registry
        run: docker push ghcr.io/makadev/ci-images/php:8.0-cli
