name: Update PHP 7.4 CLI CI Variant

on:
  push:
    paths:
      - '!**'
      - '.github/workflows/php-7.4-cli.yml'
      - 'php-7.4-cli/**'

jobs:
  update:
    name: Build and Publish PHP 7.4 CLI
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build PHP 7.4 CLI
        run: docker build php-7.4-cli  --label "org.opencontainers.image.source=https://github.com/makadev/ci-images" --tag ghcr.io/makadev/ci-images/php-7.4-cli:latest
      - name: Push PHP 7.4 CLI to GitHub Container Registry
        run: docker push ghcr.io/makadev/ci-images/php-7.4-cli:latest
